#!/usr/bin/env python3
"""Builds nomadright/lexicon/native_words.txt: real Hindi/Tamil (and other Indic) words in
Devanagari form, used by native_correct.py to NEVER "correct" a real word.

Sources (development time; the output file ships with the kiosk, nothing is fetched at run time):
  1. the whole-word entries of the IndicTrans2 indic-en source vocabulary on this device
     (IndicTrans2 converts every Indic script to Devanagari before tokenising, so Tamil words
     appear there in Devanagari form; ~75k entries)
  2. every Hindi/Tamil word the kiosk itself says or shows: forms.json prompts and questions,
     the scheme catalogue, kiosk intents, UI strings (Tamil converted to Devanagari by the same
     Unicode-block offset the translator uses)
  3. optional extra transcripts passed on the command line (e.g. FLEURS train/dev .tsv files)
usage: build_native_lexicon.py [extra.tsv ...]"""
import json, os, re, sys, glob
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
VOCAB = "/home/stark-x/bhashini_models/nmt/checkpoints/indic-en/ct2_int8_model/source_vocabulary.txt"
WORD = re.compile(r"[ऀ-ॿ஀-௿]+")

def to_deva(w):
    return "".join(chr(ord(c) - 0x0B80 + 0x0900) if 0x0B80 <= ord(c) <= 0x0BFF else c for c in w)

words = set()
for line in open(VOCAB, encoding="utf-8"):
    if line.startswith("▁"):
        w = line.rstrip("\n")[1:]
        if len(w) >= 2 and re.fullmatch(r"[ऀ-ॿ]+", w):
            words.add(w)
n_vocab = len(words)

def add_text(t):
    for w in WORD.findall(t or ""):
        if len(w) >= 2:
            words.add(to_deva(w))

def walk(o):
    if isinstance(o, str): add_text(o)
    elif isinstance(o, dict): [walk(v) for v in o.values()]
    elif isinstance(o, list): [walk(v) for v in o]

walk(json.load(open(os.path.join(ROOT, "nomadright", "forms", "forms.json"), encoding="utf-8")))
walk(json.load(open(os.path.join(ROOT, "nomadright", "scheme_intel", "scheme_catalog.json"), encoding="utf-8")))
sys.path.insert(0, os.path.join(ROOT, "python"))
from pocketinfer.applications.nomad_right import kiosk_intents as K
walk(K.RESPONSES); walk(getattr(K, "NATIVE_PHRASES", {})); walk(K.NATIVE_WORDS)
for p in glob.glob("/home/stark-x/UI/src/i18n/strings.ts"):
    add_text(open(p, encoding="utf-8").read())
for extra in sys.argv[1:]:
    add_text(open(extra, encoding="utf-8").read())
out = os.path.join(HERE, "native_words.txt")
with open(out, "w", encoding="utf-8") as f:
    f.write("# real Indic words in Devanagari form - generated by build_native_lexicon.py, do not edit\n")
    for w in sorted(words):
        f.write(w + "\n")
print(f"{out}: {len(words)} words ({n_vocab} from the IndicTrans2 vocabulary)")
